# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7c8988b94c319cbf89b71dc25a2549a618f150e88dc46194f3639d9173f9526de52d8e42cc290c7d836b92f29b40aae5a160e966730b79d50c5e374b061c3619

test:
  secret_key_base: 0ab00d47b134fe724ff81e2fb7f70c6db39adea87792a2a368883ad7bf7dbd16027960b8da13058d5383e3d24840fa8e86c9518a1708ac6f9905335ec432d79a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
